### ISSUE TITLE
Reconsider client-side routing

### ISSUE THREAD

**Issue by luckysori** [comit-network/droplet#78]

**Comment by thomaseizinger** [comment]
The client-side routing may easily conflict with API endpoints, we should reconsider on whether it we actually need it and at the very least choose a routing-scheme that is distinctly different from the API endpoints and any resource that might be served via bobtimus.

Also consider if the routes make sense in terms of deep-linking.

**Comment by bonomat** [comment]
If I see it correctly than we are only using this for rendering different components. The reason we went for it in the first place to improve readability in the code. 
 
Given our app has a state we can also do the rendering using that state (which we had first).

**Comment by thomaseizinger** [comment]
> If I see it correctly than we are only using this for rendering different components. The reason we went for it in the first place to improve readability in the code.

Correct.

The point of client-side routing is separate functionally different states (which are most likely different screens) from each other.

What is important with client-side routing is deep-linking. In other words, reloading the page using the same URL should send the user back to the state in which they left it. Can we do this with our current usage of routes?

I am on the fence on whether or not client-side routing makes sense for us.

I think instead of routes, simply querying the wallet for the locked / unlocked state might make more sense. In a way, this is similar to a logged-in / logged-out behaviour and that is hardly ever represented using a URL but rather with a session-cookie.

For the state of having completed the swap, it might still be useful to create a route. We probably want to add the transaction ID to the URL so that deep linking works. Something like: 

```
https://localhost:3000/swapped/cdfecccb4f0d93d52f3e01d795b6a4657c12adf5563858180dda3e48b1763658
```

**Comment by bonomat** [comment]
Maybe this will all go away once we extract the wallet into a browser extension? 

> What is important with client-side routing is deep-linking. In other words, reloading the page using the same URL should send the user back to the state in which they left it. Can we do this with our current usage of routes?

As far as I can tell, there is not much state in our application besides the wallet status. 
The main thing that is rendered differently is the big blue button in the middle which changes from `create wallet` to `unlock wallet` to `swap`. All this information can be easily retrieved by the wallet. 

The other state is the `swapped` done state. We can easily remove this by just showing a [_Toast_](https://chakra-ui.com/docs/feedback/toast) with the transaction ID and a link to blockstream.com .

That way we don't need any client side routing.

**Comment by thomaseizinger** [comment]
> Maybe this will all go away once we extract the wallet into a browser extension?

Potentially yes.

> That way we don't **need** any client side routing.

(Emphasis mine) I don't think we should be trying to work-around it if it is the right thing from a UX perspective to have a separate route.
Having completed a swap is a state that is worthwhile to go back to (to check the confirmations for example or to send the link to someone else).

I do agree that we should not store the locked / unlocked state in the URL. The canonical source for this is the wallet.

What about the following:

1. Render the create wallet / unlock / swap button based on the wallet's state, no routing here
2. Use routing to either render the swap page or a page that displays you a link to the block explorer and something like "congratulations, your swap is complete!" From here, we should probably link back to the root with a "Swap again?" link.
